# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_mgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DevType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('priority', models.SmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3')], default=0)),
                ('progress', models.CharField(max_length=20)),
                ('review_time', models.DateTimeField()),
                ('dev_start_time', models.DateTimeField()),
                ('dev_complete_time', models.DateTimeField()),
                ('test_start_time', models.DateTimeField()),
                ('release_time', models.DateTimeField()),
                ('dev_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_mgr.DevModel')),
                ('dev_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_mgr.DevType')),
                ('development_liable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_liable', to=settings.AUTH_USER_MODEL)),
                ('product_liable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_liable', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_mgr.Version')),
            ],
        ),
    ]
